//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ComtaxApp.com.work121 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ComTaxServiceSoap", Namespace="http://work121.com/")]
    public partial class ComTaxService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetImageDataOperationCompleted;
        
        private UserCredentials userCredentialsValueField;
        
        private System.Threading.SendOrPostCallback SetTDFDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTDFDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransitDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGSTINDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetGSTINCerificationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ComTaxService() {
            this.Url = "http://work121.com/webservice/ComtaxService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public UserCredentials UserCredentialsValue {
            get {
                return this.userCredentialsValueField;
            }
            set {
                this.userCredentialsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetImageDataCompletedEventHandler GetImageDataCompleted;
        
        /// <remarks/>
        public event SetTDFDataCompletedEventHandler SetTDFDataCompleted;
        
        /// <remarks/>
        public event GetTDFDataCompletedEventHandler GetTDFDataCompleted;
        
        /// <remarks/>
        public event GetTransitDataCompletedEventHandler GetTransitDataCompleted;
        
        /// <remarks/>
        public event GetGSTINDataCompletedEventHandler GetGSTINDataCompleted;
        
        /// <remarks/>
        public event SetGSTINCerificationCompletedEventHandler SetGSTINCerificationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://work121.com/GetImageData", RequestNamespace="http://work121.com/", ResponseNamespace="http://work121.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetImageData(string filetype, string id) {
            object[] results = this.Invoke("GetImageData", new object[] {
                        filetype,
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetImageDataAsync(string filetype, string id) {
            this.GetImageDataAsync(filetype, id, null);
        }
        
        /// <remarks/>
        public void GetImageDataAsync(string filetype, string id, object userState) {
            if ((this.GetImageDataOperationCompleted == null)) {
                this.GetImageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImageDataOperationCompleted);
            }
            this.InvokeAsync("GetImageData", new object[] {
                        filetype,
                        id}, this.GetImageDataOperationCompleted, userState);
        }
        
        private void OnGetImageDataOperationCompleted(object arg) {
            if ((this.GetImageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImageDataCompleted(this, new GetImageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://work121.com/SetTDFData", RequestNamespace="http://work121.com/", ResponseNamespace="http://work121.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetTDFData(string associateID, string associatepwd, string licenceId, string tdfjson, string appdatetime) {
            object[] results = this.Invoke("SetTDFData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        tdfjson,
                        appdatetime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetTDFDataAsync(string associateID, string associatepwd, string licenceId, string tdfjson, string appdatetime) {
            this.SetTDFDataAsync(associateID, associatepwd, licenceId, tdfjson, appdatetime, null);
        }
        
        /// <remarks/>
        public void SetTDFDataAsync(string associateID, string associatepwd, string licenceId, string tdfjson, string appdatetime, object userState) {
            if ((this.SetTDFDataOperationCompleted == null)) {
                this.SetTDFDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetTDFDataOperationCompleted);
            }
            this.InvokeAsync("SetTDFData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        tdfjson,
                        appdatetime}, this.SetTDFDataOperationCompleted, userState);
        }
        
        private void OnSetTDFDataOperationCompleted(object arg) {
            if ((this.SetTDFDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetTDFDataCompleted(this, new SetTDFDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://work121.com/GetTDFData", RequestNamespace="http://work121.com/", ResponseNamespace="http://work121.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TDFData[] GetTDFData(string associateID, string associatepwd, string licenceId, string searchkey) {
            object[] results = this.Invoke("GetTDFData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        searchkey});
            return ((TDFData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTDFDataAsync(string associateID, string associatepwd, string licenceId, string searchkey) {
            this.GetTDFDataAsync(associateID, associatepwd, licenceId, searchkey, null);
        }
        
        /// <remarks/>
        public void GetTDFDataAsync(string associateID, string associatepwd, string licenceId, string searchkey, object userState) {
            if ((this.GetTDFDataOperationCompleted == null)) {
                this.GetTDFDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTDFDataOperationCompleted);
            }
            this.InvokeAsync("GetTDFData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        searchkey}, this.GetTDFDataOperationCompleted, userState);
        }
        
        private void OnGetTDFDataOperationCompleted(object arg) {
            if ((this.GetTDFDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTDFDataCompleted(this, new GetTDFDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://work121.com/GetTransitData", RequestNamespace="http://work121.com/", ResponseNamespace="http://work121.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransitData[] GetTransitData(string associateID, string associatepwd, string licenceId, string searchkey) {
            object[] results = this.Invoke("GetTransitData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        searchkey});
            return ((TransitData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTransitDataAsync(string associateID, string associatepwd, string licenceId, string searchkey) {
            this.GetTransitDataAsync(associateID, associatepwd, licenceId, searchkey, null);
        }
        
        /// <remarks/>
        public void GetTransitDataAsync(string associateID, string associatepwd, string licenceId, string searchkey, object userState) {
            if ((this.GetTransitDataOperationCompleted == null)) {
                this.GetTransitDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransitDataOperationCompleted);
            }
            this.InvokeAsync("GetTransitData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        searchkey}, this.GetTransitDataOperationCompleted, userState);
        }
        
        private void OnGetTransitDataOperationCompleted(object arg) {
            if ((this.GetTransitDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransitDataCompleted(this, new GetTransitDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://work121.com/GetGSTINData", RequestNamespace="http://work121.com/", ResponseNamespace="http://work121.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GSTINData[] GetGSTINData(string associateID, string associatepwd, string licenceId, string searchkey) {
            object[] results = this.Invoke("GetGSTINData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        searchkey});
            return ((GSTINData[])(results[0]));
        }
        
        /// <remarks/>
        public void GetGSTINDataAsync(string associateID, string associatepwd, string licenceId, string searchkey) {
            this.GetGSTINDataAsync(associateID, associatepwd, licenceId, searchkey, null);
        }
        
        /// <remarks/>
        public void GetGSTINDataAsync(string associateID, string associatepwd, string licenceId, string searchkey, object userState) {
            if ((this.GetGSTINDataOperationCompleted == null)) {
                this.GetGSTINDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGSTINDataOperationCompleted);
            }
            this.InvokeAsync("GetGSTINData", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        searchkey}, this.GetGSTINDataOperationCompleted, userState);
        }
        
        private void OnGetGSTINDataOperationCompleted(object arg) {
            if ((this.GetGSTINDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGSTINDataCompleted(this, new GetGSTINDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UserCredentialsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://work121.com/SetGSTINCerification", RequestNamespace="http://work121.com/", ResponseNamespace="http://work121.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetGSTINCerification(string associateID, string associatepwd, string licenceId, string gstinverfjson) {
            object[] results = this.Invoke("SetGSTINCerification", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        gstinverfjson});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetGSTINCerificationAsync(string associateID, string associatepwd, string licenceId, string gstinverfjson) {
            this.SetGSTINCerificationAsync(associateID, associatepwd, licenceId, gstinverfjson, null);
        }
        
        /// <remarks/>
        public void SetGSTINCerificationAsync(string associateID, string associatepwd, string licenceId, string gstinverfjson, object userState) {
            if ((this.SetGSTINCerificationOperationCompleted == null)) {
                this.SetGSTINCerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetGSTINCerificationOperationCompleted);
            }
            this.InvokeAsync("SetGSTINCerification", new object[] {
                        associateID,
                        associatepwd,
                        licenceId,
                        gstinverfjson}, this.SetGSTINCerificationOperationCompleted, userState);
        }
        
        private void OnSetGSTINCerificationOperationCompleted(object arg) {
            if ((this.SetGSTINCerificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetGSTINCerificationCompleted(this, new SetGSTINCerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://work121.com/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://work121.com/", IsNullable=false)]
    public partial class UserCredentials : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://work121.com/")]
    public partial class GSTINData {
        
        private string errorMessageField;
        
        private string pANCardNoField;
        
        private string stateCodeField;
        
        private string mobileNoField;
        
        private string emailIDField;
        
        private string tradeNameField;
        
        private string regNameField;
        
        private string compIndField;
        
        private string signIndField;
        
        private string gSTINIDField;
        
        private string assignedToField;
        
        private string stateJursdCdField;
        
        private string cntrJursdCdField;
        
        private string regStartDateField;
        
        private string liabDateField;
        
        private string fDateField;
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string PANCardNo {
            get {
                return this.pANCardNoField;
            }
            set {
                this.pANCardNoField = value;
            }
        }
        
        /// <remarks/>
        public string StateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNo {
            get {
                return this.mobileNoField;
            }
            set {
                this.mobileNoField = value;
            }
        }
        
        /// <remarks/>
        public string EmailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
            }
        }
        
        /// <remarks/>
        public string TradeName {
            get {
                return this.tradeNameField;
            }
            set {
                this.tradeNameField = value;
            }
        }
        
        /// <remarks/>
        public string RegName {
            get {
                return this.regNameField;
            }
            set {
                this.regNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompInd {
            get {
                return this.compIndField;
            }
            set {
                this.compIndField = value;
            }
        }
        
        /// <remarks/>
        public string SignInd {
            get {
                return this.signIndField;
            }
            set {
                this.signIndField = value;
            }
        }
        
        /// <remarks/>
        public string GSTINID {
            get {
                return this.gSTINIDField;
            }
            set {
                this.gSTINIDField = value;
            }
        }
        
        /// <remarks/>
        public string AssignedTo {
            get {
                return this.assignedToField;
            }
            set {
                this.assignedToField = value;
            }
        }
        
        /// <remarks/>
        public string StateJursdCd {
            get {
                return this.stateJursdCdField;
            }
            set {
                this.stateJursdCdField = value;
            }
        }
        
        /// <remarks/>
        public string CntrJursdCd {
            get {
                return this.cntrJursdCdField;
            }
            set {
                this.cntrJursdCdField = value;
            }
        }
        
        /// <remarks/>
        public string RegStartDate {
            get {
                return this.regStartDateField;
            }
            set {
                this.regStartDateField = value;
            }
        }
        
        /// <remarks/>
        public string LiabDate {
            get {
                return this.liabDateField;
            }
            set {
                this.liabDateField = value;
            }
        }
        
        /// <remarks/>
        public string FDate {
            get {
                return this.fDateField;
            }
            set {
                this.fDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://work121.com/")]
    public partial class TransitData {
        
        private string errorMessageField;
        
        private string transitNoField;
        
        private string vehicleNoField;
        
        private string genDateField;
        
        private string dPlaceField;
        
        private string destPlaceField;
        
        private string entryLocationField;
        
        private string exitLocationField;
        
        private string prominentLocationField;
        
        private string descGoodField;
        
        private string valueGoodField;
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string TransitNo {
            get {
                return this.transitNoField;
            }
            set {
                this.transitNoField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleNo {
            get {
                return this.vehicleNoField;
            }
            set {
                this.vehicleNoField = value;
            }
        }
        
        /// <remarks/>
        public string GenDate {
            get {
                return this.genDateField;
            }
            set {
                this.genDateField = value;
            }
        }
        
        /// <remarks/>
        public string DPlace {
            get {
                return this.dPlaceField;
            }
            set {
                this.dPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string DestPlace {
            get {
                return this.destPlaceField;
            }
            set {
                this.destPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string EntryLocation {
            get {
                return this.entryLocationField;
            }
            set {
                this.entryLocationField = value;
            }
        }
        
        /// <remarks/>
        public string ExitLocation {
            get {
                return this.exitLocationField;
            }
            set {
                this.exitLocationField = value;
            }
        }
        
        /// <remarks/>
        public string ProminentLocation {
            get {
                return this.prominentLocationField;
            }
            set {
                this.prominentLocationField = value;
            }
        }
        
        /// <remarks/>
        public string DescGood {
            get {
                return this.descGoodField;
            }
            set {
                this.descGoodField = value;
            }
        }
        
        /// <remarks/>
        public string ValueGood {
            get {
                return this.valueGoodField;
            }
            set {
                this.valueGoodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://work121.com/")]
    public partial class TDFData {
        
        private string errorMessageField;
        
        private string tDFTypeField;
        
        private string purchaserTinField;
        
        private string sellerTinField;
        
        private string amountField;
        
        private string invoiceNoField;
        
        private string challanNoField;
        
        private string geolocationField;
        
        private string[] tDFFilesField;
        
        private string mobileUnitNameField;
        
        private string vehicleNumberField;
        
        private string reverseGeoCodeField;
        
        private string invoiceDateField;
        
        private string mainCommodityField;
        
        private string iMEI1Field;
        
        private string iMEI2Field;
        
        private string iMSI1Field;
        
        private string iMSI2Field;
        
        private string versionNameField;
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string TDFType {
            get {
                return this.tDFTypeField;
            }
            set {
                this.tDFTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PurchaserTin {
            get {
                return this.purchaserTinField;
            }
            set {
                this.purchaserTinField = value;
            }
        }
        
        /// <remarks/>
        public string SellerTin {
            get {
                return this.sellerTinField;
            }
            set {
                this.sellerTinField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public string ChallanNo {
            get {
                return this.challanNoField;
            }
            set {
                this.challanNoField = value;
            }
        }
        
        /// <remarks/>
        public string geolocation {
            get {
                return this.geolocationField;
            }
            set {
                this.geolocationField = value;
            }
        }
        
        /// <remarks/>
        public string[] TDFFiles {
            get {
                return this.tDFFilesField;
            }
            set {
                this.tDFFilesField = value;
            }
        }
        
        /// <remarks/>
        public string MobileUnitName {
            get {
                return this.mobileUnitNameField;
            }
            set {
                this.mobileUnitNameField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleNumber {
            get {
                return this.vehicleNumberField;
            }
            set {
                this.vehicleNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReverseGeoCode {
            get {
                return this.reverseGeoCodeField;
            }
            set {
                this.reverseGeoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string MainCommodity {
            get {
                return this.mainCommodityField;
            }
            set {
                this.mainCommodityField = value;
            }
        }
        
        /// <remarks/>
        public string IMEI1 {
            get {
                return this.iMEI1Field;
            }
            set {
                this.iMEI1Field = value;
            }
        }
        
        /// <remarks/>
        public string IMEI2 {
            get {
                return this.iMEI2Field;
            }
            set {
                this.iMEI2Field = value;
            }
        }
        
        /// <remarks/>
        public string IMSI1 {
            get {
                return this.iMSI1Field;
            }
            set {
                this.iMSI1Field = value;
            }
        }
        
        /// <remarks/>
        public string IMSI2 {
            get {
                return this.iMSI2Field;
            }
            set {
                this.iMSI2Field = value;
            }
        }
        
        /// <remarks/>
        public string versionName {
            get {
                return this.versionNameField;
            }
            set {
                this.versionNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetImageDataCompletedEventHandler(object sender, GetImageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetTDFDataCompletedEventHandler(object sender, SetTDFDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTDFDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetTDFDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTDFDataCompletedEventHandler(object sender, GetTDFDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTDFDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTDFDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TDFData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TDFData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTransitDataCompletedEventHandler(object sender, GetTransitDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransitDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransitDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransitData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransitData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetGSTINDataCompletedEventHandler(object sender, GetGSTINDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGSTINDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGSTINDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GSTINData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GSTINData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SetGSTINCerificationCompletedEventHandler(object sender, SetGSTINCerificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetGSTINCerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetGSTINCerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591